[package]
name = "day10"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.15", features = ["derive"]}
env_logger = "0.11"
itertools = "0.13"
log = "0.4"
regex = {version = "1.11.1"}
petgraph = "0.6"

